export const actionTypes = {
  NEW_MOVE: "NEW_MOVE",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  PROMOTION_OPEN: "PROMOTION_OPEN",
  CLOSE_PROMOTION_SQUARE: "CLOSE_PROMOTION_SQUARE",
  CAN_CASTLE: "CAN_CASTLE",
  STALEMATE: "STALEMATE",
  NEW_GAME: "NEW_GAME",
  INSUFFICIENT_MATERIAL: "INSUFFICIENT_MATERIAL",
  WIN: "WIN",
  TAKE_BACK: "TAKE_BACK",
};
